baseURL: "https://carlossanabriam.github.io"
languageCode: "en-us"
title: "Carlos Sanabria Miranda"
theme: hugo-profile

# Pagination (https://gohugo.io/templates/pagination/)
Paginate: 3

# Google Analytics (https://gohugo.io/templates/internal/#google-analytics)
#googleAnalytics: G-MEASUREMENT_ID # TODO
# Disqus (https://gohugo.io/templates/internal/#disqus)
#disqusShortname: your-disqus-shortname # TODO

# Markdown and other markup related configuration (https://gohugo.io/getting-started/configuration-markup)
markup:
  goldmark: # Goldmark is from Hugo 0.60 the default library used for Markdown
    renderer:
      unsafe: true # render raw HTMLs

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1
#
#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  # Open Graph (https://gohugo.io/templates/internal/#open-graph) and Twitter Cards (https://gohugo.io/templates/internal/#twitter-cards) metadata
  title: "Carlos Sanabria Miranda"
  description: My personal website
#  images: # TODO
#    - site-feature-image.jpg
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Carlos."
    subtitle: "I build data platforms"
    content: "A passionate big data engineer.
        I tend to make use of modern technologies to implement, test, deploy, automate and maintain data driven apps."
    image: /images/hero.png
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1t1belGdS1F8FjLF4mlUyTauDK4P43VQC/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        # https://fontawesome.com/v5/search
        # Font Awesome icons are designed on grid and share a consistent height.
        # But they vary in width depending on how wide or narrow each symbol is.
        # If you prefer to work with icons that have a consistent width, adding fa-fw will render each icon using the same width.
        # https://fontawesome.com/docs/web/style/fixed-width
        - icon: fab fa-github fa-fw
          url: "https://github.com/CarlosSanabriaM"
        - icon: fab fa-linkedin fa-fw
          url: "https://www.linkedin.com/in/CarlosSanabriaM"
        - icon: fas fa-code-branch fa-fw
          url: "https://github.com/CarlosSanabriaM/carlossanabriam.github.io"
#      customIcons:
#        - icon: /fav.png
#          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a Software Engineer with a huge passion for data and analytics, and the Cloud computing ecosystem.
      I truly believe in the DevOps culture and its benefits.
      I cannot imagine a project without CI/CD, automation or monitoring.
      I also have a strong interest in the IoT world and its application in multiple fields.

      I am currently working as a Big Data Engineer at [Accenture](https://www.accenture.com/),
      where I have designed, implemented, deployed, monitored and maintained multiple streaming applications
      for processing data in real time in the AWS cloud.
      
      I was honored with the [Final Degree Award](https://drive.google.com/file/d/1krHMfnayADHeWNg5gBrqJwiVuEcmiIC1/view?usp=sharing)
      for the highest GPA of the Software Engineer Degree.
    skills:
      enable: true
      title: "Here are a few technologies I have been working with a lot recently:"
      items:
        - "Flink"
        - "Kafka"
        - "Redis"
        - "ArangoDB"
        - "EMR"
        - "EKS"
        - "Hadoop Yarn"
        - "Kubernetes"
        - "Ansible"
        - "Docker"
        - "Grafana"
        - "Kibana"
        - "Java"
        - "Python"

  # Footer
  footer:
    recentPosts: false # TODO: Uncomment when posts are available
    socialNetworks:
      github: "https://github.com/CarlosSanabriaM"
      linkedin: "https://www.linkedin.com/in/CarlosSanabriaM"
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com
