baseURL: https://carlossanabriam.github.io
languageCode: en-us
title: Carlos Sanabria Miranda
theme: hugo-profile

# Pagination (https://gohugo.io/templates/pagination/)
Paginate: 3

# Google Analytics (https://gohugo.io/templates/internal/#google-analytics)
#googleAnalytics: G-MEASUREMENT_ID # TODO
# Disqus (https://gohugo.io/templates/internal/#disqus)
#disqusShortname: your-disqus-shortname # TODO

# Markdown and other markup related configuration (https://gohugo.io/getting-started/configuration-markup)
markup:
  goldmark: # Goldmark is from Hugo 0.60 the default library used for Markdown
    renderer:
      unsafe: true # render raw HTMLs

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1
#
#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  # Open Graph (https://gohugo.io/templates/internal/#open-graph) and Twitter Cards (https://gohugo.io/templates/internal/#twitter-cards) metadata
  title: Carlos Sanabria Miranda
  description: My personal website
#  images: # TODO
#    - site-feature-image.jpg
  # staticPath: ""  # The path to serve the static files from
  favicon: /fav.png

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    # align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: true # Disable search in the navbar, because there is not searchable content yet
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false

  # Documentation for configuring each of the following sections:
  # https://github.com/gurusabarish/hugo-profile/wiki/Pages-or-Sections

  # Hero
  hero:
    enable: true
    intro: Hi, my name is
    title: Carlos
    subtitle: A passionate Data Engineer
    content: |-
        I use modern technologies to design, implement, test, deploy, monitor and maintain data driven apps.
        I am specialized in streaming processing and Cloud computing.
    image: /images/hero.png
    socialLinks:
      fontAwesomeIcons:
        # https://fontawesome.com/v5/search
        # Font Awesome icons are designed on grid and share a consistent height.
        # But they vary in width depending on how wide or narrow each symbol is.
        # If you prefer to work with icons that have a consistent width, adding fa-fw will render each icon using the same width.
        # https://fontawesome.com/docs/web/style/fixed-width
        - icon: fab fa-github fa-fw
          url: https://github.com/CarlosSanabriaM
        - icon: fab fa-linkedin fa-fw
          url: https://www.linkedin.com/in/CarlosSanabriaM
        - icon: fas fa-code-branch fa-fw
          url: https://github.com/CarlosSanabriaM/carlossanabriam.github.io
#      customIcons:
#        - icon: /fav.png
#          url: "https://example.com"

  # About
  about:
    enable: true
    title: About Me
    image: /images/me.jpg
    content: |-
      I am a Software Engineer with a strong passion for data and analytics, and the Cloud computing ecosystem.
      I have a solid background in data streaming processing, particularly with Apache Flink, in the AWS cloud.
      I am a strong advocate of the DevOps culture and its benefits, and I cannot imagine a project without CI/CD, automation or monitoring.
      I also have a keen interest in the IoT world and its applications across various fields.

      I have +5 years of experience in the data ecosystem, and I am currently working as a Data Engineer at
      [Openbank](https://www.opendigitalservices.com/) in Spain. I also have some experience in leading
      development teams and teaching online classes.
      
      I was honored with the [Final Degree Award](https://drive.google.com/file/d/1krHMfnayADHeWNg5gBrqJwiVuEcmiIC1/view?usp=sharing)
      for the best academic record in the Software Engineer Degree.

      I’m a very curious person, always eager to learn new things and improve myself every day.
      I am very disciplined with my habits, and I always try to do my best to achieve my goals.

      As for my hobbies, I really enjoy staying active and practicing sports, especially going to the gym,
      but I am always open to exploring new sports whenever I can. I like spending time with my friends and my girlfriend,
      watching football, listening to music and podcasts, playing video games, and collecting vinyl records and anime statues.
      I am also an avid reader, particularly of personal development books, manga, and video game magazines.
      I love traveling, experiencing diverse cultures and meeting new people.
    skills:
      enable: true
      title: "These are my essential skills and the technologies in which I have the most expertise:"
      items:
        - Spanish (native)
        - "[English (C1)](https://drive.google.com/file/d/1mXeXpdDFqLQ_1aZJO9-XDZZ3W7lqiASE/view?usp=sharing)"
        - Java
        - Python
        - Flink
        - Kafka
        - Iceberg
        - Redis
        - Docker
        - Kubernetes
        - Ansible
        - Vagrant
        - Grafana
        - Kibana
        - Spring
        - AWS

  # Experience
  experience:
    enable: true
    companies:
      - company: Openbank
        companyUrl: https://www.opendigitalservices.com/
        jobs:
          - job: Associate Manager I - Big Data - Data Lake
            date: May 2023 - Present
            info:
              enable: false
            content: |
              * Was a member of the __platform team__, a __data engineering group__ responsible for managing the __data lake__ and developing and maintaining various __data tools__ to support and enhance the __data infrastructure__, as well as other __data teams__.
              * __Improved__ and __optimized__ a __Flink__ job responsible for __generating real-time alerts__ based on __core banking__ data.
              * __Implemented__ a __Flink__ job responsible for making __core banking__ data and other systems' information available in the __Data Lake__ in __near real-time__, using __Iceberg__ tables. Implemented and orchestrated the execution of various __table maintenance operations__.
              * __Improved__ the internal __flow orchestrator__ (__Spring Boot__ + __Angular__) and helped make it cloud provider agnostic.
              * __Technologies:__ Java, Scala, Flink, Iceberg, Avro, Schema Registry, Spring, AWS (Kinesis, Glue, Lambda, CloudWatch, CloudFormation).

      - company: UAX
        companyUrl: https://www.uax.com/
        jobs:
          - job: Associate Professor
            date: Oct. 2023 - Present
            info:
              enable: true
              content: Universidad Alfonso X el Sabio
            content: |
              * Professor of __Python__ in the subject __Programming Languages__ (SM142050) of the [Master's Degree in Artificial Intelligence](https://www.uax.com/titulaciones/master-inteligencia-artificial).
              * Professor and coordinator of the subject __Cloud Software Development and DevOps__ (C0342506) of the [Bachelor's Degree in Data Science and Artificial Intelligence](https://www.uax.com/titulaciones/grado-online-en-ciencia-de-datos-e-inteligencia-artificial).

      - company: Accenture
        companyUrl: https://www.accenture.com
        jobs:
          - job: Team Lead / Consultant - Big Data & Cloud
            date: Dec. 2022 - May 2023
            info:
              enable: false
            content: |
              * Defined __cost and security controls__ for the __Big Data Cloud platform (AWS) of a banking project valued at €10M__, using AWS services such as __Lambda, CloudWatch, SNS, IAM, and CloudFormation__.
              * __Trained 50 people__ in __Python__ and __streaming (Kafka + Flink)__ in __2 editions__ of an __internal Accenture bootcamp__.
              * __Led the training__ in Python, PySpark, and AWS for a group of __13 people__ (junior and senior profiles). __Ensured__ that all __obtained__ the __AWS Certified Cloud Practitioner__ certification. __Integrated them into the project__ and __facilitated their collaboration and growth__.
              * Acted as a __mentor__ for 3 people, __internship supervisor__ for 3 students, and __thesis advisor__ for one Bachelor's thesis.

          - job: Advanced App Engineering Senior Analyst - Big Data
            date: Dec. 2020 - Dec. 2022
            info:
              enable: false
            content: |
              * Developed and __end-to-end solution__ for __monitoring__ __Flink__ and __EMR__; which includes the collection, processing and loading of Flink/EMR __metrics__ and __logs__; and the creation of __dashboards__ in __Grafana__ and __Kibana__ for their visualization and analysis.
              * __Automated__ the __configuration__ of the __EMR__ clusters through __Ansible__, following a __GitOps__ philosophy.
              * Implemented a __Continuous Delivery__ process for deploying __Flink__ jobs on __EMR__, based on the __declarative__ paradigm.
              * Developed a __proof of concept__ of the new __Flink SQL__ version, to __homologate__ it and promote its usage within the project.
              * Improved and __evolved__ our __Java framework__ based on __Flink__ with abstractions over __Flink SQL__, which __simplified the development__ of streaming applications focused on __joining__ event streams.
              * __Reduced AWS infrastructure costs__ by __60%__ by __optimizing EMR__ and __ElastiCache__ instances.
              * Maintained __close communication__ with the client's development teams, focusing on decision-making and continuous improvement.
              * Took part in __on-call duty__, handling __maintenance__ of __production__ applications and __resolving__ numerous __incidents__.
              * Conducted __technical interviews with 3 candidates__ to select a new member for our project’s __development team__.
              * __Led a team of 3 developers__ to implement and deploy numerous __streaming projects__ with __Flink__.
              * __Helped win__ an __RFP__ (Request For Proposals) from one of the largest insurance companies in the market, where I __designed__ a __serverless architecture__ based on __microservices__ on __AWS__.
                * It was a __resounding success__, as __the project was awarded to Accenture__ and we received __personal recognition from the CDO__ (Chief Data Officer) of the insurance company.
              * Was __selected__ by __Accenture__ to participate in the __exclusive TechStar program__, where I had the opportunity to further develop my technical, interpersonal, and management skills.
                * __Less than 1%__ of the analysts and consultants of Accenture Technology can participate in this program.

          - job: Advanced App Engineering Analyst - Big Data
            date: May 2019 - Dec. 2020
            info:
              enable: false
            content: |
              * Designed and implemented a __Java framework based on Flink__ that facilitated the development of __streaming applications__
                * This framework abstracts several common components, including: security configurations, read/write events from/to Kafka, N-N joins between events, generation of custom metrics, and timestamps management.
              * Implemented and deployed numerous __streaming applications__ on __AWS__ using the previous framework, services such as __EMR, S3, ElastiCache, EC2, and Certificate Manager__, and technologies such as __Flink, Kafka, Redis, CouchBase, and Hadoop YARN__.
              * Automated numerous internal processes using __Python and Bash scripts__.
              * Contributed to the adoption of a __testing culture__ focused on specification-based techniques (__Equivalent Class Partitioning__) and structure-based techniques (__MCDC - Modified condition/decision coverage__).

          - job: Artificial Intelligence Intern
            date: Feb. 2019 - May 2019
            featuredLink:
              enable: true
              name: Project website
              url: http://topics-and-summary-web-front.herokuapp.com
            info:
              enable: true
              content: The project I worked on in this internship was presented as my final degree project.
            content: |
              * Developed a __Python library__ for __topic identification__ in a collection of documents, the __classification of documents__ into those topics, and the __generation of extractive text summaries__, using __NLP__ (Natural Language Processing) techniques.
              * Developed a __REST API in Flask__ and a __frontend in Angular__, which eased the interaction with a collection of documents.

      - company: UniOvi
        companyUrl: https://www.uniovi.es
        jobs:
          - job: Computer Science Intern
            date: Oct. 2017 - May 2018
            info:
              enable: true
              content: Universidad de Oviedo
            content: |
              * __Installed__ several __software packages__ and __repaired__ multiple __hardware devices__. __Managed the inventory__ and __resolved__ a range of issues for both students and teachers, with a particular focus on problems related to __Active Directory__.

  # Education
  education:
    enable: true
    items:
      - title: Bachelor's Degree in Software Engineering
        school:
          name: Universidad de Oviedo
          url: https://ingenieriainformatica.uniovi.es/infoacademica/grado
        date: 2015–2019
        GPA: 9.312 out of 10 · 3.66 out of 4
        content: |-
          * __Awarded 28 honors__
          * __Final Degree Award for best academic record__
          * __Grace Hopper Award for academic excellence__
          * __Final Degree Project__: Web application for the classification of text documents and the generation of extractive summaries
            * [Source code](https://github.com/CarlosSanabriaM/degree-final-project)
            * [Website](http://topics-and-summary-web-front.herokuapp.com)
        featuredLink:
          enable: true
          name: Final Degree Award
          url: https://drive.google.com/file/d/1krHMfnayADHeWNg5gBrqJwiVuEcmiIC1/view?usp=sharing

  # Achievements
  achievements:
    enable: true
    items:
      - title: AWS Certified Cloud Practitioner
        url: https://www.credly.com/badges/ac01d725-09f7-474c-980b-7d23c952a202/public_url
        image: /images/certifications/aws-certified-cloud-practitioner.png
        imageWidthPercentage: 50%
        content: July 2020
      
      - title: AWS Certified Solutions Architect – Associate
        url: https://www.credly.com/badges/cc930e4d-3b8b-4c81-b59a-068efffc6778/public_url
        image: /images/certifications/aws-certified-solutions-architect-associate.png
        imageWidthPercentage: 50%
        content: March 2021
      
      - title: AWS Certified Data Analytics – Specialty
        url: https://www.credly.com/badges/a25d383c-e9dc-4615-87c0-3248cca98b1b/public_url
        image: /images/certifications/aws-certified-data-analytics-specialty.png
        imageWidthPercentage: 50%
        content: July 2021
      
      - title: "Microsoft Certified: Azure Fundamentals"
        url: https://www.credly.com/badges/11094dde-fba8-4151-97a4-620312171991/public_url
        image: /images/certifications/microsoft-certified-azure-fundamentals.png
        imageWidthPercentage: 50%
        content: November 2020
      
      - title: "Microsoft Certified: Azure Data Fundamentals"
        url: https://www.credly.com/badges/27ef3e46-2484-4337-8edb-34162d412e60/public_url
        image: /images/certifications/microsoft-certified-azure-data-fundamentals.png
        imageWidthPercentage: 50%
        content: January 2021
      
      - title: Certified Kubernetes Application Developer
        url: https://www.credly.com/badges/641ae1d8-6742-4fd0-887a-76cf394114c2/public_url
        image: /images/certifications/ckad-certified-kubernetes-application-developer.png
        imageWidthPercentage: 50%
        content: April 2022

      - title: Accenture TechStar 2022
        content: |-
          I was selected by Accenture to participate in the exclusive TechStar program,
          where I had the opportunity to further develop my technical, interpersonal, and management skills.
        url: https://www.linkedin.com/pulse/accenture-technology-stars-2018-sam-liew/

      - title: Final Degree Award
        content: I received this award for achieving the best academic record (the highest GPA) in my cohort for the Bachelor's Degree in Software Engineering.
        url: https://drive.google.com/file/d/1krHMfnayADHeWNg5gBrqJwiVuEcmiIC1/view?usp=sharing

      - title: Grace Hopper Award
        content: I received this award in recognition of my academic excellence in the Bachelor's Degree in Software Engineering.

  # Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:sanabria.miranda.carlos@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  # Footer
  footer:
    #recentPosts: false # TODO: Uncomment when posts are available
    socialNetworks:
      github: https://github.com/CarlosSanabriaM
      linkedin: https://www.linkedin.com/in/CarlosSanabriaM
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com
